### ISSUE TITLE
load_cropper_without_selection is not defined

### ISSUE THREAD

**Issue by Dartanjan** [Aminadav/screenshot-extension#9] opened 2015-08-20 08:13 UTC
When I try to use the region crop tool, nothing happens. This is what shows up in the Console:

Uncaught ReferenceError: load_cropper_without_selection is not defined
(anonymous function) @ VM437:1

Any resolution to this?

**Comment by Aminadav** [comment] 2018-02-14 17:41
It should be fixed. Please test the last version.

**Closed by Aminadav** 2018-02-14 17:41 UTC

**Comment by constantin-iliescu** [comment] 2018-03-01 09:47
Just installed the extension freshly updated chrome and the issue is still there:

Uncaught ReferenceError: load_cropper_without_selection is not defined
(anonymous) @ VM73:1
